Add news file
cnerg/pyne pull request #39
Opened 2019-01-09 18:41 UTC by bam241

adding a news file to `pymoab_cleanup`

I never know how to fille those files properly.... so please let me know what I did not do right...

2019-01-09 23:23 UTC, gonuke requested changes
We probably want a little more commentary on each of these or on subsets of these to describe which use case this is for...

2019-01-09 23:23 UTC, gonuke commented on news/pymoab_cleanup.rst
> +   - iMesh.mesh.getTagHandle('cell_number') -> mesh.cell_number
These changes are not due to pyMOAB. This was already available in IMeshTag but was rarely used.

When the tag is created on a mesh object, it is added to the attribute list of that mesh object.

2019-01-09 23:23 UTC, gonuke commented on news/pymoab_cleanup.rst
> +   - del mtag[XXXX] -> mesh.mesh.tag_delete_data(mtag, XXXX)
We should make sure that this is correct with respect to #29

2019-01-09 23:23 UTC, gonuke commented on news/pymoab_cleanup.rst
> +   - mesh.createTag(tag_name, num_e_groups * max_num_cells, float) -> mesh.tag(tag_name, np.zeros(float_tag_size, dtype = float), 'nat_mesh', size = float_tag_size, dtype = float)
```suggestion
   - mesh.createTag(tag_name, length_of_vector, float) -> mesh.tag(tag_name, np.zeros(length_of_vector, dtype = float), 'nat_mesh', size = length_of_vector, dtype = float)
```

2019-01-11 16:38 UTC, ngranda commented on news/pymoab_cleanup.rst
> +* PyNE can be build with PyMOAB whitout DAGMC with limited capabilities
```suggestion
* PyNE can be built with PyMOAB whitout DAGMC with limited capabilities
```

2019-01-11 19:07 UTC, bam241 commented
@gonuke do you like that better ?
(this is not necessary finished yet...)

2019-01-12 21:19 UTC, gonuke approved these changes

2019-01-12 21:20 UTC, gonuke commented
thanks @bam241

2019-01-12 21:20 UTC, merged