R2s script add test
cnerg/pyne pull request #51
Opened 2019-01-18 20:36 UTC by zxkjack123

This PR provides test functions and files for r2s script using a given simple geometry for both voxel and sub-voxel r2s. It is a solution for issue #34 .

Major changes:
- Add test functions in tests/test_r2s.py
- Add a soft link from pyne/r2s.py to tests/r2s.py
- Add a series of files used by the test functions

2019-01-22 17:38 UTC, zxkjack123 commented
This PR fails the 'build_py2' test because the error of import dagmc. The reason of the error is that 'build_py2' is a build without the options of '--moab' and '--dagmc'.
@gonuke @pshriwise I think we can ignore the test failure of 'build_py2' for this PR, as it requires pymoab, how can we expect that it works without pymoab?

2019-01-25 16:37 UTC, gonuke requested changes
There should be separate tests for `step1` and `step2`

`step2` test should depend on expected results of `step1` test rather than observed results of `step1` test

2019-01-25 16:37 UTC, gonuke commented on tests/test_r2s.py
> +    # test voxel r2s
add a `try` block to import dagmc and if it fails, skip the test  - see `test_partisn.py` for an example

2019-01-25 16:41 UTC, gonuke commented
Conceptually:
* move testing of `step1` results before running `step2`
* put all `step2` actions in a separate function
* begin `step2` function by copying expected results of `step1` to overwrite observed results

2019-01-31 23:30 UTC, gonuke commented
I propose we defer this and PR it into pyne/pyne once we have merged pymoab

2019-02-08 22:08 UTC, zxkjack123 commented
DO NOT MERGE!
An error founded when running unstructured r2s step1. Error message:
```
Traceback (most recent call last):
  File "r2s.py", line 227, in <module>
    main()
  File "r2s.py", line 222, in main
    step1()
  File "r2s.py", line 149, in step1
    tag.delete()
  File "/root/.local/lib/python2.7/site-packages/pyne/mesh.py", line 111, in delete
    del self[:]
  File "/root/.local/lib/python2.7/site-packages/pyne/mesh.py", line 188, in __delitem__
    raise AttributeError(msg)
AttributeError: the material property tag 'atoms_per_molecule' may not be deleted
```
It seems that the `tag.delete()` is trying to delete a tag named `atoms_per_molecule`, then the error raised. I made this commit to enable others to repeat this error and debug with example files.

2019-02-15 16:48 UTC, zxkjack123 commented
Rebase after the merge of #68.

2019-02-15 17:25 UTC, zxkjack123 commented
Put this PR to pyne/pyne after pymoab get merged into pyne/pyne.

2019-02-15 17:25 UTC, closed without merging